INSERT INTO ITEM (ID,NAME,PRICE) VALUES(01,'Chocopie',5.0);
INSERT INTO ITEM (ID,NAME,PRICE) VALUES(02,'Peach Milk',10.0);
INSERT INTO ITEM (ID,NAME,PRICE) VALUES(03,'Lays Chips',20.0);

INSERT INTO ORDERITEM (ID,NAME,PRICE) VALUES(01,'Chocopie',5.0);
INSERT INTO ORDERITEM (ID,NAME,PRICE) VALUES(02,'Peach Milk',10.0);
INSERT INTO ORDERITEM (ID,NAME,PRICE) VALUES(03,'Lays Chips',20.0);

INSERT INTO BUYER (ID,NAME,PASSWORD) VALUES(01,'lynn','lynn');
INSERT INTO SELLER (ID,NAME,PASSWORD,CART) VALUES(01,'thet','thet');
INSERT INTO RIDER (ID,NAME,PASSWORD,CART) VALUES(01,'swe','swe');

INSERT INTO ORDER (ID,AMOUNT) VALUES(01,150.0);
